In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('salary_data.csv')

In [4]:
df.head()

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

# Mean

In [5]:
df.mean()

YearsExperience        5.313333
Salary             76003.000000
dtype: float64

In [6]:
print(df['Salary'].mean())

76003.0

# Median

In [7]:
df.median()

YearsExperience        4.7
Salary             65237.0
dtype: float64

In [8]:
print(df['Salary'].median())

65237.0

# Mode

In [9]:
print(df['Salary'].mode())

0      37731.0
1      39343.0
2      39891.0
3      43525.0
4      46205.0
5      54445.0
6      55794.0
7      56642.0
8      56957.0
9      57081.0
10     57189.0
11     60150.0
12     61111.0
13     63218.0
14     64445.0
15     66029.0
16     67938.0
17     81363.0
18     83088.0
19     91738.0
20     93940.0
21     98273.0
22    101302.0
23    105582.0
24    109431.0
25    112635.0
26    113812.0
27    116969.0
28    121872.0
29    122391.0
Name: Salary, dtype: float64

# Variance

In [10]:
df.var()

YearsExperience    8.053609e+00
Salary             7.515510e+08
dtype: float64

In [11]:
print(df['Salary'].var())

751550960.4137931

# Standard Deviation

In [12]:
df.std()

YearsExperience        2.837888
Salary             27414.429785
dtype: float64

In [13]:
print(df['Salary'].std())

27414.4297845823

# Coefficient Of Variation(CV)

In [14]:
from scipy.stats import variation
variation(df.values)

array([0.5251297 , 0.35463929])

In [16]:
print(variation(df['Salary']))

0.3546392938275572

# Correlation

In [17]:
df.corr()

                 YearsExperience    Salary
YearsExperience         1.000000  0.978242
Salary                  0.978242  1.000000

In [19]:
print(df['Salary'].corr(df['YearsExperience']))

0.9782416184887598

# Skewness

In [20]:
df.skew()

YearsExperience    0.37956
Salary             0.35412
dtype: float64

In [22]:
print(df['Salary'].skew())

0.35411967922959153

# Standaard Error

In [23]:
df.sem()

YearsExperience       0.518125
Salary             5005.167198
dtype: float64

In [24]:
df['Salary'].sem()

np.float64(5005.167198052405)

# Z-Score

In [25]:
from scipy.stats import stats

df.apply(stats.zscore)

C:\Users\HP\AppData\Local\Temp\ipykernel_6356\3833364753.py:3: DeprecationWarning: Please import `zscore` from the `scipy.stats` namespace; the `scipy.stats.stats` namespace is deprecated and will be removed in SciPy 2.0.0.
  df.apply(stats.zscore)

    YearsExperience    Salary
0         -1.510053 -1.360113
1         -1.438373 -1.105527
2         -1.366693 -1.419919
3         -1.187494 -1.204957
4         -1.115814 -1.339781
5         -0.864935 -0.718307
6         -0.829096 -0.588158
7         -0.757416 -0.799817
8         -0.757416 -0.428810
9         -0.578216 -0.698013
10        -0.506537 -0.474333
11        -0.470697 -0.749769
12        -0.470697 -0.706620
13        -0.434857 -0.702020
14        -0.291498 -0.552504
15        -0.148138 -0.299217
16        -0.076458 -0.370043
17        -0.004779  0.262859
18         0.210261  0.198860
19         0.246100  0.665476
20         0.532819  0.583780
21         0.640339  0.826233
22         0.927058  0.938611
23         1.034577  1.402741
24         1.213777  1.240203
25         1.321296  1.097402
26         1.500496  1.519868
27         1.536336  1.359074
28         1.787215  1.721028
29         1.858894  1.701773

In [26]:
stats.zscore(df['Salary'])

C:\Users\HP\AppData\Local\Temp\ipykernel_6356\3453814175.py:1: DeprecationWarning: Please import `zscore` from the `scipy.stats` namespace; the `scipy.stats.stats` namespace is deprecated and will be removed in SciPy 2.0.0.
  stats.zscore(df['Salary'])

array([-1.36011263, -1.10552744, -1.419919  , -1.20495739, -1.33978143,
       -0.71830716, -0.58815781, -0.79981746, -0.42881019, -0.69801306,
       -0.47433279, -0.74976858, -0.70662043, -0.70201994, -0.55250402,
       -0.29921736, -0.37004264,  0.26285865,  0.19885989,  0.66547573,
        0.58377993,  0.82623317,  0.93861127,  1.40274136,  1.24020308,
        1.09740238,  1.51986835,  1.3590738 ,  1.72102849,  1.70177321])

# Degree Of Freedom

In [27]:
a = df.shape[0]
b = df.shape[1]

degree_of_freedom = a-b;
print(degree_of_freedom)

28

# Sum of Square Regression (SSR)

In [37]:
x = df.iloc[:,:-1].values
x

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [39]:
y = df.iloc[:,1].values
y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [40]:
y_mean = np.mean(y)